### ISSUE TITLE
[BUG] Error while running `npm run examples`

### ISSUE THREAD

**Issue by yqlu1119** [mathematic-inc/ts-japi#10]
When I run `npm run examples`, the following errors show up:

![image](https://user-images.githubusercontent.com/45544769/87967320-7fa83000-ca73-11ea-9f8d-498b0e87fa17.png)

Can I get some help on this? Thank you!

**Comment by jrandolf** [comment]
Some arguments were switched. Should be fixed now.

**Comment by yqlu1119** [comment]
Thank you very much for the quick fix!! I am still seeing the following TypeError
![image](https://user-images.githubusercontent.com/45544769/87968572-7ae47b80-ca75-11ea-9231-70621b826744.png)

Would be great if i can get some help, as I really want to use this npm package in my project🙏🙏🙏

**Comment by jrandolf** [comment]
Could you tell me what version of node you are using?

**Comment by yqlu1119** [comment]
v10.19.0

**Comment by yqlu1119** [comment]
Just upgraded node to 12.14.1 and it works now!! Thank you very much!!!!

**Comment by jrandolf** [comment]
10.19.0 does not support [`flatMap`](https://node.green/#ES2019-features-Array-prototype--flat--flatMap-).
